### PR TITLE
Update tabCenterReborn.css

### PR DESCRIPTION
**Pull request by codewzrd**
Moved the close button to the left and added transition logic to shift the favicon and tab text to the right.

### CODE REVIEW

**Comment by codewzrd** [comment]
I don't like the animation when the cursor moves to a different tab.

**Comment by Freeplayg** [comment]
Instead of moving the content to the right, you could just replace the icon w/ the close button.

**Comment by ranmaru22** [comment]
Hmm, I personally prefer the close icon on the right side, but I think this is still a good change, because some people have modded the CSS so that the sidebar doesn't expand and only shows the favicons. With this, they can still close the tabs with the mouse.

Also, it's easier to comment out than to copy in, so I think we can merge this.

**Comment by Freeplayg** [comment]
It has a weird jumping behavior which I kinda hate.

https://user-images.githubusercontent.com/40742947/125175793-793b2880-e19c-11eb-82bd-51575fbb0d98.mp4

**Comment by Freeplayg** [comment]
After a little bit of using this, i found myself accidentally closing tabs. Because now, I have to move my mouse over the sidebar to open it, then move it to the right of the X button to click onto it.

**Comment by codewzrd** [comment]
@Freeplayg, yeah it takes a little getting used to.

What bothered me was whenever I wanted to close a tab, I would have to hover over the sidebar, which would expand, then move my mouse all the way to the right to close the tab.
With this change, I can close the tab right away, and select a tab by moving the cursor a few pixels over.

Good news is that this is optional so can be turned off... maybe we should start with this disabled and users can turn it on if they wish.

**Comment by Freeplayg** [comment]
I've always just use middle-click to close tabs, I think having it off by default would be good.

**Pull request merged**
