### PR TITLE
Better support for non-compact mode

### PR DESCRIPTION
**Pull request by Freeplayg**
https://user-images.githubusercontent.com/40742947/186820838-2aed9d76-7fc9-4353-bf27-6a813975c483.mp4

### CODE REVIEW

**Comment by Freeplayg** [comment]
Would also be good to update this line "Compact Mode: either /”Dynamic”/ or /”Enabled”/. It works with /”Disabled”/ too but looks nicer with only favicons." in the readme if this is merged

**Comment by Freeplayg** [comment]
Hold on, I need to fix something with the audio icon, first.

**Comment by Freeplayg** [comment]
I think it's safe to merge, now

**Review by ranmaru22 — APPROVED** [review]

**Comment by ranmaru22** [comment]
Thanks, this is nice. I might actually use this myself. :)

**Pull request merged**
